[tool.briefcase]
project_name = "Flip The Coin"
bundle = "ml.amarquaye"
version = "0.0.1"
url = "https://amarquaye.ml/flipthecoin"
license = "BSD license"
author = 'Jesse Amarquaye'
author_email = "llordjesse@gmail.com"

[tool.briefcase.app.flipthecoin]
formal_name = "Flip The Coin"
description = "An interactive game which allows you to guess whether a coin will be flipped to display heads or tails"
icon = "src/flipthecoin/resources/flipthecoin"
sources = ['src/flipthecoin']
requires = [
]


[tool.briefcase.app.flipthecoin.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.flipthecoin.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.flipthecoin.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.flipthecoin.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.flipthecoin.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.flipthecoin.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.flipthecoin.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.flipthecoin.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
